// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPvzOScLxynHZK8PXdn9mz7exHetbTKQc',
    appId: '1:97265599953:web:d9de020c1915094d4b0cf0',
    messagingSenderId: '97265599953',
    projectId: 'flutter-awm',
    authDomain: 'flutter-awm.firebaseapp.com',
    storageBucket: 'flutter-awm.appspot.com',
    measurementId: 'G-ZR0ZNSP99Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlYPusioKRewGHEaHc-6MunxYr0H3vliM',
    appId: '1:97265599953:android:48c2ebc7c34f38b04b0cf0',
    messagingSenderId: '97265599953',
    projectId: 'flutter-awm',
    storageBucket: 'flutter-awm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhTMQm5w4OATgG92hnsIq_XD71o5FerVk',
    appId: '1:97265599953:ios:fd1e9935c7981f3d4b0cf0',
    messagingSenderId: '97265599953',
    projectId: 'flutter-awm',
    storageBucket: 'flutter-awm.appspot.com',
    iosClientId: '97265599953-v4918pps9i3ss3cj2d3iejd0tm3j3rtt.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhTMQm5w4OATgG92hnsIq_XD71o5FerVk',
    appId: '1:97265599953:ios:fd1e9935c7981f3d4b0cf0',
    messagingSenderId: '97265599953',
    projectId: 'flutter-awm',
    storageBucket: 'flutter-awm.appspot.com',
    iosClientId: '97265599953-v4918pps9i3ss3cj2d3iejd0tm3j3rtt.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );
}
